version: '3.7'

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chatop
      POSTGRES_PASSWORD: chatOperator
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6
    command: redis-server --appendonly yes --requirepass chatOperator
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=chatOperator
    volumes:
      - redis:/data

  minio:
    restart: always
    image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    ports:
      - '9000:9000'
      - '9001:9001'
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_HTTP_TRACE: /root/.minio/trace.log
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio

volumes:
  redis:
  postgres:
  minio_data:
  minio_config:
